# Development Stage
FROM node:22-alpine AS dev

#Install git
RUN apk add --no-cache git

# Set working directory
WORKDIR /app

# Copy dependency manifests
COPY package*.json ./

# Install all dependencies including dev ones
RUN npm install

# Copy full source code
COPY . .

# Expose the development port
EXPOSE 9003

# Default command for development (e.g., Vite, nodemon, etc.)
CMD ["npm", "run", "start"]
